FROM python:3.8.3-alpine

COPY . .

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install -r requirements.txt

COPY ./entrypoint.prod.sh .
ENTRYPOINT ["./entrypoint.prod.sh"]